### ISSUE TITLE
与成语库的拼音数据做了下差分，发现不少生成的拼音存在出入

### ISSUE THREAD

**Issue by ZaneYork** [antfu/handle#11]
差分数据来源: https://github.com/pwxcoo/chinese-xinhua

差分结果附在附件中了，存在2579处不一致。可以作为校对参考，不一定是本项目存在问题。
[成语拼音差分.xlsx](https://github.com/antfu/handle/files/8057609/default.xlsx)

**Comment by antfu** [comment]
可能是当初预处理的时候出了问题，欢迎直接 PR
