### ISSUE TITLE
注音错误

### ISSUE THREAD

**Issue by lifenjoiner** [antfu/handle#16]
之怒
https://github.com/antfu/handle/blob/71ba67b705c531b01f1c81d71222fef9807775c6/src/data/idioms.json#L12725

肩
https://github.com/antfu/handle/blob/71ba67b705c531b01f1c81d71222fef9807775c6/src/data/idioms.json#L7733

加
https://github.com/antfu/handle/blob/71ba67b705c531b01f1c81d71222fef9807775c6/src/data/idioms.json#L29291

**Comment by antfu** [comment]
PR welcome :)

**Comment by lifenjoiner** [comment]
It's really easy changes. Just change it is OK for me :)

**Comment by taoyouh** [comment]
These changes are already fixed in the latest version.
