### ISSUE TITLE
能否加入一个可随时查看的声母-韵母表

### ISSUE THREAD

**Issue by Neubulae** [antfu/handle#2]
其他Wordle Clone会有这么一个表格帮你自动eliminate, 但是汉兜没有…
（顺便今天的题目u和ü搞混了真的好吗（

**Comment by unickhow** [comment]
其他 wordle 都是限制使用 custom keyboard，相較之下我覺得漢兜很好用 😂
現況也許可以先包含在「提示」裡面？
以注音為例拉個概念圖
![image](https://user-images.githubusercontent.com/22793771/153117066-f4dc858e-5f12-4b1f-a2c4-738e6e70d159.png)

「不包含」的區塊在第一次輸入後才出現，甚至在輸入後可以讓「提示」有個計數告知提示更新？
