### ISSUE TITLE
请问困难模式，是哪里有变化

### ISSUE THREAD

**Issue by HollisMeynell** [antfu/handle#22]
如题

**Comment by antfu** [comment]
暂时只是隐藏提示入口，后续会再考虑在其他方面增加难度

**Comment by HollisMeynell** [comment]
> 暂时只是隐藏提示输入，可能会再考虑在其他方面增加难度

有个建议，您可以试试困难模式与目前版本保持一致，对非困难模式的拼音提醒，例如答案中包含"百"，"兴"这两个字，如果猜'冰'的位置错误会得到全棕色的拼音提示，对于新人可能难以理解，认为答案包含bing1这个读音的字，新的'简单'模式希望对错误的声母，韵母声调组合进行区分(例如正确的组合会有浅棕色的背景提示，  声母，韵母均包含但是组合错误没有)
