### ISSUE TITLE
注音错误

### ISSUE THREAD

**Issue by hhhxiao** [antfu/handle#3]
泣不成声的`泣`是第四声不是第三声
无穷无尽的穷声调应该在`o`而不是`i`上
另外是否考虑给输入加个成语筛选，不然我填`啊对对对`这种都行

**Comment by antfu** [comment]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/11247099/152989385-15020535-d0a9-44d9-be90-564c5a27030c.png">
