### ISSUE TITLE
使用汉典数据为汉兜的成语标注拼音

### ISSUE THREAD

**Issue by wangyi041228** [antfu/handle#45]
https://github.com/wangyi041228/handle_src_data_idioms.json

**Comment by antfu** [comment]
感谢整理，刚刚推送了实验性的严格模式。欢迎 PR 添加缺失的成语

**Comment by wangyi041228** [comment]
chinese-xinhua项目和汉典在线数据都有大量错误，我对有拼音差异的部分全部检查了一遍，留下汉典没收录的137个文字条目。
汉兜项目结构最近有变，我就不PR了，如需要我修订的成语拼音请随意自取。

**Comment by antfu** [comment]
我写了一些脚步去获取汉典的数据，顺便优化了一下打包的体积。项目的结构应该暂时不会再变了，你可以参考 https://github.com/antfu/handle#%E6%88%90%E8%AF%AD%E5%8B%98%E8%AF%AF
