### ISSUE TITLE
一些拼音存在错误

### ISSUE THREAD

**Issue by dynilath** [antfu/handle#46]
|词语|汉兜的拼音|正确的拼音
-|-|-
阿猫阿狗|ē māo ē gǒu|ā māo ā gǒu
阿鼻地狱|ē  bí dì yù|ā bí dì yù
失张失志|sh zhng sh zhì|shī zhāng shī zhì
榆木圪垯|yú mù gē dá|yú mù gē da

**Comment by antfu** [comment]
Thanks!
