### ISSUE TITLE
期望分享的时候能有复制图片到剪切板功能

### ISSUE THREAD

**Issue by linsizao** [antfu/handle#48]
![QQ20220307-105858](https://user-images.githubusercontent.com/30763679/156960299-6e982016-baac-471e-be28-1a572c0b4956.png)

**Comment by MarvinXu** [comment]
右键可以复制图片啊

**Comment by linsizao** [comment]
> 右键可以复制图片啊

哈哈是我傻了

**Comment by linsizao** [comment]
右键可以复制图片
