### ISSUE TITLE
yun dun的韵母没有区分

### ISSUE THREAD

**Issue by licstar** [antfu/handle#51]
yun的韵母应该是ün吧。
我看到作者已经很仔细地处理了j、q、x、y和u的组合，会改成ü。不过好像漏了un和ün的区分，同样和jqxy组合都会简写

**Comment by licstar** [comment]
感觉#52修了一个ue 的问题，并没有修un 和ün的问题啊

**Comment by toyobayashi** [comment]
@licstar 修了吧
![image](https://user-images.githubusercontent.com/23353576/157686819-6a2c9752-fda5-4db4-a3be-7f59466c9e64.png)
