### ISSUE TITLE
美国西海岸在进入夏令时之后变成每天凌晨1点刷新而不是12点了

### ISSUE THREAD

**Issue by ZaHong** [antfu/handle#56]
![image](https://user-images.githubusercontent.com/45635887/158319883-70b544be-888e-4339-80b0-4f4fddd63fdb.png)
可以看到当前时间11：28，但是提示hai有一个半小时才会有下一题。

**Comment by antfu** [comment]
并不了解怎么修复也无法测试，PR welcome

**Comment by yuanxili1** [comment]
北美中部时区也有相同问题
