### ISSUE TITLE
分享图中文字位置不正确

### ISSUE THREAD

**Issue by wrj2009** [antfu/handle#63]
在 `iPhone 6s Plus、iOS 15.4、Safari 浏览器` 以及 `iPad Air、iPadOS 15.4、Safari 浏览器` 上发现了这个问题，其他设备上都没有。
分享图中，汉字位置都偏上，顶部和底部居中显示的内容都变成了左对齐，但其他界面都是正常的。

---

这是生成的分享图：
![生成的分享图](https://user-images.githubusercontent.com/67864454/160268307-f8d23cb8-df75-42ce-b26c-8a314bae423b.jpg)

关闭遮罩时的分享图：
![关闭遮罩时的分享图](https://user-images.githubusercontent.com/67864454/160268356-e4138b01-f11b-4348-b7b1-a6279ffc9633.jpg)

**Comment by antfu** [comment]
据说是 iOS 15.4 引入的改动造成的 bug 暂时原因不明

**Comment by antfu** [comment]
已修复
