### ISSUE TITLE
ü 的展示

### ISSUE THREAD

**Issue by yangmingshan** [antfu/handle#74]
https://github.com/antfu/handle/commit/94f31d855ad5ed699c0a06992592d138b180c21c 这个 Commit 特地将一部分 `u` 改成了 `ü`，如 `yun` -> `yün`。我不太理解是为什么，因为按照注释链接的百度百科，对 `ü` 的规范用法是：

> ü列的韵母，前面没有[声母](https://baike.baidu.com/item/%E5%A3%B0%E6%AF%8D)的时候，写成yu（迂），yue（约）yuan（冤）yun（晕）；ü上两点省略。

> ü列的韵母跟声母j，q，x拼的时候，写成：ju（居），qu（区），xu（虚），ü上两点也省略；但是跟声母n，l拼的时候，仍然写成nü（女），lü（吕）。

我从别处查到的信息也与百度百科一致，似乎修改之前才是正确的。

**Comment by antfu** [comment]
yu 的 u 和 wu 的 u 虽都写作 u 但实则是两个不同的韵母，汉兜作为一个游戏更看重线索的连贯性（音的正确性），而非写法的绝对正确性。
