### ISSUE TITLE
今日音调可能有错误

### ISSUE THREAD

**Issue by mhggpo** [antfu/handle#79]
![Screenshot_2022-06-26-01-17-46-911_com android browser](https://user-images.githubusercontent.com/42616077/175784027-2eabda3f-bc1c-4f2b-8c19-8822514dfce6.jpg)
“土”按常理应该为三声

**Comment by Allustrate** [comment]
*剧透警告*
*Spoiler Alert*

**Comment by chucklu** [comment]
@antfu  这个还没部署吗？今天测试泥古不化的时候，发现拼音也是错误的。
虽然源码里面，好像有修正了？https://github.com/ZaneYork/handle/blame/045317ccb5aaa87ac834a6628eac029e1cd96e67/src/data/idioms.json#L15184
["泥古不化","ni4 gu3 bu4 hua4"],
