### ISSUE TITLE
记分应能重置

### ISSUE THREAD

**Issue by GH01** [antfu/handle#88]
### Clear and concise description of the problem

目前记分好像无法重置。

（我本想清除浏览器相关cookie，然而没有搜到`antfu`相关项……）

### Suggested solution

应允许用户重置记分。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wyhooo** [comment]
You should clear localStorage instead :)
